In [78]:
import torch
import matplotlib.pyplot as plt
import numpy as np

In [79]:
X = torch.tensor([
    [1.0, 2.0],
    [2.0, 4.0],
    [3.0, 6.0],
    [4.0, 8.0],
    [5.0, 10.0]
])

In [80]:
mean = X.mean(dim=0)
mean

tensor([3., 6.])

In [81]:
X_c = X-mean
X_c

tensor([[-2., -4.],
        [-1., -2.],
        [ 0.,  0.],
        [ 1.,  2.],
        [ 2.,  4.]])

In [82]:
# we need covariance matrix first
# we can do torch.cov() but to learn we shall implement the actual code

$$\mathbf{\Sigma} = \frac{1}{N} \mathbf{X}_c^T \mathbf{X}_c$$

In [83]:
# Original X
#    ↓
# Center X
#    ↓
# Covariance matrix
#    ↓
# Eigenvectors + Eigenvalues
#    ↓
# Sort by eigenvalues
#    ↓
# Choose top components
#    ↓
# Project X onto them
#    ↓
# Reduced X

# this is the procedure basically for now and you know where we stand

In [84]:
cov_matrix = (X_c.T @ X_c)/len(X)

In [85]:
cov_matrix

tensor([[2., 4.],
        [4., 8.]])

In [86]:
# now coming to eigen bhai log
eigenval, eigenvec = torch.linalg.eigh(cov_matrix)

In [87]:
eigenval, eigenvec

(tensor([ 0., 10.]),
 tensor([[-0.8944,  0.4472],
         [ 0.4472,  0.8944]]))

In [88]:
# bcoz eigh() sorts asc, we need to reverse the order before using the components
eigenval = eigenval.flip(0)
eigenvec = eigenvec.flip(1)

print(eigenval)
print(eigenvec)

tensor([10.,  0.])
tensor([[ 0.4472, -0.8944],
        [ 0.8944,  0.4472]])


In [89]:
# explained variance ratio:

$$\lambda_1 = 8, \quad \lambda_2 = 2$$

$$8 + 2 = 10$$

$$\text{EVR}_i = \frac{\lambda_i}{\sum_{j} \lambda_j}$$

$$\text{EVR}_1 = \frac{8}{10} = 0.8$$

$$80\%$$

$$\text{EVR}_2 = \frac{2}{10} = 0.2$$

$$20\%$$

In [90]:
# tell how much of original features does it hold?
# PC1 → 40%
# PC2 → 25%
# PC3 → 15%
# PC4 → 8%
# PC5 → 4%
# ...

# supports cummulative
# PC1              40%
# PC1 + PC2        65%
# PC1 + PC2 + PC3  80%
# PC1 ... PC4      88%
# PC1 ... PC5      92%

In [91]:
evr = (eigenval / eigenval.sum())
evr

tensor([1., 0.])

In [92]:
pc1 = eigenvec[:, 0]
pc1

tensor([0.4472, 0.8944])

In [93]:
X_red = X_c @ pc1
X_red

tensor([-4.4721, -2.2361,  0.0000,  2.2361,  4.4721])

In [94]:
cumulative_variance = torch.cumsum(evr, dim=0)
cumulative_variance

tensor([1., 1.])